TheRenegadeCoder/sample-programs-website

- projects/hello-world/_posts/2020-09-30-tex.md
> Added the Hello World article for Tex.

- projects/hello-world/_posts/2020-09-30-typescript.md
> Added the Hello World Article for TypeScript

- projects/bubble-sort/_posts/2020-09-30-go.md
> Add the Bubble Sort Article for Go.

- projects/hello-world/_posts/2020-09-30-emojicode.md
> Added the Hello World Article for Emojicode.

- projects/hello-world/_posts/2020-09-30-typescript.md
Also made a minor grammar fix.
> Updated the how to Run Section for Hello World Article of Typescript.

- _data/authors.yml
> Added Bio to Authors File

- _data/authors.yml
- projects/fizz-buzz/_posts/2020-10-05-c.md
Created an article for FizzBuzz in C for issue #217 
If there are any changes, do tell them.
> Created an article for FizzBuzz in C.

- _data/authors.yml
I decided to fix an issue with the authors file. I also decided to sort it at the same time.
> Sorted Authors File Alphabetically

- _data/authors.yml
> Added GoodbyeBlues to Authors

- projects/baklava/_posts/2020-10-05-c.md
- projects/binary-search/_posts/2018-12-19-python.md
- projects/bubble-sort/_posts/2020-09-30-go.md
- projects/even-odd/_posts/2019-10-16-python.md
- projects/even-odd/_posts/2020-10-06-c.md
- projects/fibonacci/_posts/2020-10-13-python.md
- projects/fizz-buzz/_posts/2018-11-06-java.md
- projects/fizz-buzz/_posts/2018-11-24-swift.md
- projects/fizz-buzz/_posts/2018-12-11-powershell.md
- projects/fizz-buzz/_posts/2018-12-15-python.md
- projects/fizz-buzz/_posts/2019-10-01-javascript.md
- projects/fizz-buzz/_posts/2019-10-18-lisp.md
- projects/fizz-buzz/_posts/2020-08-30-befunge.md
- projects/fizz-buzz/_posts/2020-10-05-c.md
- projects/fizz-buzz/index.md
- projects/hello-world/_posts/2018-11-17-red.md
- projects/hello-world/_posts/2018-12-05-rust.md
Added featured-images from assets/images
> Added Fibonacci in Python Article and Added Some Images

- .github/workflows/main.yml
It looks like some of my dependencies can't handle the latest version of Python (3.9). I'll try forcing Python 3.8 and see how things go.
> Enforced Python 3.8 Build

- projects/linear-search/index.md
I'm trying to standardize documentation to make our lives easier.
> Added Testing Table to Linear Search Project

- projects/hello-world/_posts/2018-11-01-brainfuck.md
- projects/hello-world/_posts/2018-11-01-dart.md
- projects/hello-world/_posts/2018-11-01-lua.md
- projects/hello-world/_posts/2018-11-01-moonscript.md
- projects/hello-world/_posts/2018-11-01-opa.md
- projects/hello-world/_posts/2018-11-01-powershell.md
- projects/hello-world/_posts/2018-11-01-r.md
> Updated Several Hello World Featured Images

- projects/convex-hull/index.md
Added test cases for ConvexHull algorithms
> Added Convex Hull Test Cases

- projects/longest-palindrome-substring/index.md
Current tests were a little messy. I changed them to be standardized like our usual tests. There could probably be some additional alphanumeric tests and whatnot, but I didn't bother to include them.
> Simplified LPS Testing

- .github/workflows/main.yml
The build is breaking with write access issues. I don't know why exactly, so we're trying this.
> Forced Myself as Commit Author

- .github/workflows/main.yml
I thought this was a cool idea!
> Added Credit to TheRenegadeCoder Org to Image Commit

- projects/remove-all-whitespace/index.md
I realized we were missing a description. In an attempt to improve the quality of our documentation, I decided to revisit it.
> Added a Description to the Remove All Whitespace Article

- projects/import-export/_posts/2019-10-01-javascript.md
- projects/import-export/_posts/2019-10-01-typescript.md
- projects/import-export/index.md
Someone started adding the code for import/export in C, so I decided to revisit the docs to make sure they were quality.
> Updated Import/Export Requirements

- _layouts/default.html
It's a small thing, but this type of stuff could help me support  maintenance of these repos long term.
> Added Coil Web Monetization

- templates/LANGUAGE_ARTICLE_TEMPLATE.md
Added several new sections:
- Resources
- Features
> Reworked Language Article Template

- _data/authors.yml
- projects/fizz-buzz/_posts/2021-12-11-rust.md
Project documentation for the sample program FizzBuzz in Rust. This PR fixes issue #184.
> add fizzbuzz in rust documentation

- scripts/automate.py
Now, we can get rid of the wiki!
> Duplicated Wiki Features on Website

- sources/programs/binary-search/java/front_matter.yaml
- sources/programs/binary-search/java/how-to-implement-the-solution.md
- sources/programs/binary-search/java/how-to-run-the-solution.md
> Added Binary Search in Java

- sources/projects/palindromic-number/description.md
- sources/projects/palindromic-number/front_matter.yaml
- sources/projects/palindromic-number/invalid-tests.md
- sources/projects/palindromic-number/requirements.md
- sources/projects/palindromic-number/testing.md
- sources/projects/palindromic-number/valid-tests.md
The current test cases leave a bit to be desired, so I upgraded them to the valid/invalid format.
> Reworked Palindromic Number to Use More Effective Test Cases

- docs/projects/fibonacci/index.md
> Modify Fibonacci in Every Language

- docs/projects/duplicate-character-counter/index.md
> Modify Duplicate Character Counter

- sources/projects/fibonacci/testing.md
> Modify Fibonacci in Every Language Article

- sources/projects/duplicate-character-counter/requirements.md
- sources/projects/duplicate-character-counter/testing.md
> Modify Duplicate Character Counter in Every Language Article

- .github/pull_request_template.md
> Fix Typo in Pull Request Template

- sources/projects/fibonacci/testing.md
> Modify Fibonacci in Every Language (3rd time the charm?)

- sources/projects/depth-first-search/requirements.md
> Fix error message in Requirements section of Depth First Search

- sources/projects/maximum-array-rotation/description.md
> Modify Maximum Array Rotation in Every Language

- sources/projects/minimum-spanning-tree/description.md
> Add Diagrams for Minimum Spanning Tree

- sources/projects/maximum-subarray/testing.md
> Fix error message for Maximum Subarray

- sources/projects/sleep-sort/requirements.md
- sources/projects/sleep-sort/testing.md
fixes #518 
Also need to add invalid test cases to Testing section
> Fix Requirements section of Sleep Sort

- sources/languages/euphoria/description.md
- sources/languages/euphoria/front_matter.yaml
> Add Euphoria Language Article

- sources/languages/euphoria/description.md
> Fix typos and enhance content for Euphoria Language Article

- docs/assets/css/style.scss
I fixed #533 . The [Jekyll Dinky Theme](https://github.com/broccolini/dinky/blob/master/stylesheets/styles.css#L5-L23) puts everything with a vertical-align of baseline, including the `<sup>` tag (see [line 9](https://github.com/broccolini/dinky/blob/master/stylesheets/styles.css#L9)). This PR puts the `<sup>` tag back to what it's supposed to be. Even though, it's not currently used, I also fixed the `<sub>` tag.
> Fix superscript

- requirements.txt
- scripts/automate.py
Testing out the beta of the official SnakeMD release. Seems to be working. Will be using this as proof of what SnakeMD is capable of.
> Updated Requirements to SnakeMD 2.0.0b1

- sources/languages/phix/description.md
- sources/languages/phix/front_matter.yaml
> Add Phix Language Article

- generate.sh
- requirements.txt
- scripts/automate.py
I fixed #545 . With this fix, the "Hello World in Piet" displays like this:
> Allow images to be displayed instead of code for graphical language such as Piet

- scripts/automate.py
> Don't strip leading spaces in code

- scripts/automate.py
> Expand tabs to 4 spaces for sample program code

- requirements.txt
- scripts/automate.py
This PR contains the following:
- Fixes #573 
- Fixes #574 
- Fixes #575
> Separate code and article authors

- sources/programs/file-input-output/gnu-make/how-to-implement-the-solution.md
- sources/programs/file-input-output/gnu-make/how-to-run-the-solution.md
> Add File Input Output in Gnu Make

- sources/programs/quine/gnu-make/how-to-implement-the-solution.md
- sources/programs/quine/gnu-make/how-to-run-the-solution.md
> Add Quine in Gnu Make Article

- sources/programs/fizz-buzz/gnu-make/how-to-implement-the-solution.md
- sources/programs/fizz-buzz/gnu-make/how-to-run-the-solution.md
> Add Fizz Buzz in Gnu Make Article

- sources/programs/hello-world/hack/how-to-implement-the-solution.md
- sources/programs/hello-world/hack/how-to-run-the-solution.md
I fixed #590 . This article needs to be merged after TheRenegadeCoder/sample-programs#3173 is merged.
> Modify Hello World in Hack

- sources/programs/baklava/gnu-make/how-to-implement-solution.md
- sources/programs/baklava/gnu-make/how-to-run-the-solution.md
> Add Baklava in Gnu Make Article

- sources/languages/unicat/description.md
> Add Unicat Language Article

- sources/languages/unicat/description.md
> Fix typo in Unicat Language article

- requirements.txt
> Update to glotter 0.8.0

- sources/languages/commodore-basic/description.md
> Add Commodore BASIC language article

- sources/projects/transpose-matrix/description.md
```
[x] Right :)
[ x ] Wrong :(
```
- I fixed #606 
> Modify Transpose Matrix Project Article

- .github/workflows/main.yml
> Update action versions to latest major rev

- sources/languages/c-star/description.md
```
[x] Right :)
[ x ] Wrong :(
```
- I fixed #612 
> Modify C* Language Article

- sources/programs/hello-world/c-star/how-to-implement-the-solution.md
- sources/programs/hello-world/c-star/how-to-run-the-solution.md
```
[x] Right :)
[ x ] Wrong :(
```
- I fixed #613 
> Modify Hello World in C*

- .github/workflows/main.yml
- generate.sh
- scripts/automate.py
```
[x] Right :)
[ x ] Wrong :(
```
- I fixed #636
I also updated the following:
- Modified `generate.sh` to support other OSes
- Updated `actions/setup-python` version to suppress deprecated Node issue (see [this](https://github.com/TheRenegadeCoder/sample-programs-website/actions/runs/11088550779) for an example)
[1]: …
> Generate 'do not edit' comment in 'docs' files

- sources/languages/arkscript/description.md
> feat(language): updating arkscript documentation

- scripts/automate.py
> Add counts to pages

- sources/programs/hello-world/tex/how-to-implement-the-solution.md
- sources/programs/hello-world/tex/how-to-run-the-solution.md
```
[x] Right :)
[ x ] Wrong :(
```
- I fixed #640 
> Modify Hello World in Tex

- .github/CONTRIBUTING.md
- .github/workflows/main.yml
- requirements.txt
I fixed #645 . Also, updated workflow to python 3.9
> Update to glotter 0.10.0 and subete 0.20.0

- README.md
- docs/_includes/twitter_card.html
As far as I know, this is the only reference of the account on the site, but I'm leaving this as a draft as I look through the repo (i.e., run some quick searches). 
I fixed #653
> Removed Twitter References

- generate.sh
- scripts/automate.py
> Add ability to use local repo content for the website instead of pulling it from GitHub
